export interface AfricanCurrencyRow {
  countryCode: string;
  country: string;
  currencyCode: string;
  currencyName: string;
  usdPerUnit: number;
}

// Baseline defaults used for initialization/fallback. Admin can override at runtime.
export const AFRICAN_CURRENCY_BASELINE: AfricanCurrencyRow[] = [
  { countryCode: 'DZ', country: 'Algeria', currencyCode: 'DZD', currencyName: 'Algerian Dinar', usdPerUnit: 0.0074 },
  { countryCode: 'AO', country: 'Angola', currencyCode: 'AOA', currencyName: 'Angolan Kwanza', usdPerUnit: 0.0011 },
  { countryCode: 'BJ', country: 'Benin', currencyCode: 'XOF', currencyName: 'West African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'BW', country: 'Botswana', currencyCode: 'BWP', currencyName: 'Botswana Pula', usdPerUnit: 0.073 },
  { countryCode: 'BF', country: 'Burkina Faso', currencyCode: 'XOF', currencyName: 'West African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'BI', country: 'Burundi', currencyCode: 'BIF', currencyName: 'Burundian Franc', usdPerUnit: 0.00035 },
  { countryCode: 'CV', country: 'Cabo Verde', currencyCode: 'CVE', currencyName: 'Cape Verdean Escudo', usdPerUnit: 0.010 },
  { countryCode: 'CM', country: 'Cameroon', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'CF', country: 'Central African Republic', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'TD', country: 'Chad', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'KM', country: 'Comoros', currencyCode: 'KMF', currencyName: 'Comorian Franc', usdPerUnit: 0.0022 },
  { countryCode: 'CG', country: 'Congo', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'CD', country: 'Democratic Republic of the Congo', currencyCode: 'CDF', currencyName: 'Congolese Franc', usdPerUnit: 0.00035 },
  { countryCode: 'DJ', country: 'Djibouti', currencyCode: 'DJF', currencyName: 'Djiboutian Franc', usdPerUnit: 0.0056 },
  { countryCode: 'EG', country: 'Egypt', currencyCode: 'EGP', currencyName: 'Egyptian Pound', usdPerUnit: 0.020 },
  { countryCode: 'GQ', country: 'Equatorial Guinea', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'ER', country: 'Eritrea', currencyCode: 'ERN', currencyName: 'Eritrean Nakfa', usdPerUnit: 0.067 },
  { countryCode: 'SZ', country: 'Eswatini', currencyCode: 'SZL', currencyName: 'Swazi Lilangeni', usdPerUnit: 0.054 },
  { countryCode: 'ET', country: 'Ethiopia', currencyCode: 'ETB', currencyName: 'Ethiopian Birr', usdPerUnit: 0.0080 },
  { countryCode: 'GA', country: 'Gabon', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'GM', country: 'Gambia', currencyCode: 'GMD', currencyName: 'Gambian Dalasi', usdPerUnit: 0.014 },
  { countryCode: 'GH', country: 'Ghana', currencyCode: 'GHS', currencyName: 'Ghanaian Cedi', usdPerUnit: 0.077 },
  { countryCode: 'GN', country: 'Guinea', currencyCode: 'GNF', currencyName: 'Guinean Franc', usdPerUnit: 0.00012 },
  { countryCode: 'GW', country: 'Guinea-Bissau', currencyCode: 'XOF', currencyName: 'West African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'CI', country: "Cote d'Ivoire", currencyCode: 'XOF', currencyName: 'West African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'KE', country: 'Kenya', currencyCode: 'KES', currencyName: 'Kenyan Shilling', usdPerUnit: 0.0077 },
  { countryCode: 'LS', country: 'Lesotho', currencyCode: 'LSL', currencyName: 'Lesotho Loti', usdPerUnit: 0.054 },
  { countryCode: 'LR', country: 'Liberia', currencyCode: 'LRD', currencyName: 'Liberian Dollar', usdPerUnit: 0.0051 },
  { countryCode: 'LY', country: 'Libya', currencyCode: 'LYD', currencyName: 'Libyan Dinar', usdPerUnit: 0.21 },
  { countryCode: 'MG', country: 'Madagascar', currencyCode: 'MGA', currencyName: 'Malagasy Ariary', usdPerUnit: 0.00022 },
  { countryCode: 'MW', country: 'Malawi', currencyCode: 'MWK', currencyName: 'Malawian Kwacha', usdPerUnit: 0.00058 },
  { countryCode: 'ML', country: 'Mali', currencyCode: 'XOF', currencyName: 'West African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'MR', country: 'Mauritania', currencyCode: 'MRU', currencyName: 'Mauritanian Ouguiya', usdPerUnit: 0.025 },
  { countryCode: 'MU', country: 'Mauritius', currencyCode: 'MUR', currencyName: 'Mauritian Rupee', usdPerUnit: 0.022 },
  { countryCode: 'MA', country: 'Morocco', currencyCode: 'MAD', currencyName: 'Moroccan Dirham', usdPerUnit: 0.10 },
  { countryCode: 'MZ', country: 'Mozambique', currencyCode: 'MZN', currencyName: 'Mozambican Metical', usdPerUnit: 0.016 },
  { countryCode: 'NA', country: 'Namibia', currencyCode: 'NAD', currencyName: 'Namibian Dollar', usdPerUnit: 0.054 },
  { countryCode: 'NE', country: 'Niger', currencyCode: 'XOF', currencyName: 'West African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'NG', country: 'Nigeria', currencyCode: 'NGN', currencyName: 'Nigerian Naira', usdPerUnit: 0.00066 },
  { countryCode: 'RW', country: 'Rwanda', currencyCode: 'RWF', currencyName: 'Rwandan Franc', usdPerUnit: 0.00071 },
  { countryCode: 'ST', country: 'Sao Tome and Principe', currencyCode: 'STN', currencyName: 'Sao Tome and Principe Dobra', usdPerUnit: 0.044 },
  { countryCode: 'SN', country: 'Senegal', currencyCode: 'XOF', currencyName: 'West African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'SC', country: 'Seychelles', currencyCode: 'SCR', currencyName: 'Seychellois Rupee', usdPerUnit: 0.073 },
  { countryCode: 'SL', country: 'Sierra Leone', currencyCode: 'SLE', currencyName: 'Sierra Leonean Leone', usdPerUnit: 0.044 },
  { countryCode: 'SO', country: 'Somalia', currencyCode: 'SOS', currencyName: 'Somali Shilling', usdPerUnit: 0.0018 },
  { countryCode: 'ZA', country: 'South Africa', currencyCode: 'ZAR', currencyName: 'South African Rand', usdPerUnit: 0.054 },
  { countryCode: 'SS', country: 'South Sudan', currencyCode: 'SSP', currencyName: 'South Sudanese Pound', usdPerUnit: 0.0076 },
  { countryCode: 'SD', country: 'Sudan', currencyCode: 'SDG', currencyName: 'Sudanese Pound', usdPerUnit: 0.0017 },
  { countryCode: 'TZ', country: 'Tanzania', currencyCode: 'TZS', currencyName: 'Tanzanian Shilling', usdPerUnit: 0.00039 },
  { countryCode: 'TG', country: 'Togo', currencyCode: 'XOF', currencyName: 'West African CFA Franc', usdPerUnit: 0.0016 },
  { countryCode: 'TN', country: 'Tunisia', currencyCode: 'TND', currencyName: 'Tunisian Dinar', usdPerUnit: 0.32 },
  { countryCode: 'UG', country: 'Uganda', currencyCode: 'UGX', currencyName: 'Ugandan Shilling', usdPerUnit: 0.00027 },
  { countryCode: 'ZM', country: 'Zambia', currencyCode: 'ZMW', currencyName: 'Zambian Kwacha', usdPerUnit: 0.036 },
  { countryCode: 'ZW', country: 'Zimbabwe', currencyCode: 'ZiG', currencyName: 'Zimbabwe Gold', usdPerUnit: 0.074 },
];
